package com.music.echo.notune.intelligence.feedback

sealed class UserEvent {
    data class PlayStarted(val trackId: String, val title: String, val artistName: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Progress10(val trackId: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Progress25(val trackId: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Progress50(val trackId: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Progress75(val trackId: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Completed(val trackId: String, val title: String, val artistName: String, val genre: String? = null, val language: String? = null, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Skipped(val trackId: String, val title: String, val artistName: String, val playedDurationSec: Float, val genre: String? = null, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class EarlySkip(val trackId: String, val artistName: String, val playedSec: Float, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Replay(val trackId: String, val title: String, val artistName: String, val genre: String? = null, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Paused(val trackId: String, val positionMs: Long, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Resumed(val trackId: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Seeked(val trackId: String, val fromMs: Long, val toMs: Long, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Favorited(val trackId: String, val artistName: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Unfavorited(val trackId: String, val artistName: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class AddedToPlaylist(val trackId: String, val playlistName: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class RemovedFromPlaylist(val trackId: String, val playlistName: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class AddedToQueue(val trackId: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class RemovedFromQueue(val trackId: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Searched(val query: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Shared(val trackId: String, val platform: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Downloaded(val trackId: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class LyricsOpened(val trackId: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class LyricsLanguageChanged(val trackId: String, val targetLanguage: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class ArtistOpened(val artistId: String, val artistName: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class AlbumOpened(val albumId: String, val albumTitle: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class SimilarSelected(val trackId: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class RecommendationAccepted(val trackId: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class RecommendationRejected(val trackId: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class TeachRule(val rawDirective: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class ToggleTasteExclusion(val excludeCurrentSession: Boolean, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()

    // Backward compatibility aliases
    data class Play(val trackId: String, val title: String, val artistName: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Pause(val trackId: String, val positionMs: Long, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Resume(val trackId: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Skip(val trackId: String, val title: String, val artistName: String, val playedDurationSec: Float, val genre: String? = null, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Like(val trackId: String, val artistName: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Dislike(val trackId: String, val artistName: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Save(val trackId: String, val artistName: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
    data class Search(val query: String, val timestampMs: Long = System.currentTimeMillis()) : UserEvent()
}
