# Cloudflare Worker Configuration for NØTUNE Global Edge Server
name = "notune"
main = "worker.js"
compatibility_date = "2026-09-14"
account_id = "c4062f2f7ab8860317a18a059f9cd756"

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "notune_cloudflare_worker_jwt_secret_2026"

[[r2_buckets]]
binding = "NOTUNE_STORAGE"
bucket_name = "notune-media"
